# config/packages/sonata_admin.yaml

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title:      Database Administration
    title_logo: http://www.mickael-martin-nevot.com/img/logo/sypher-blue.jpg
